acceso/urls.py
from django.urls import path
from .views import LoginView, login, logout, welcome, Talleres, Detail

app_name = 'acceso'

urlpatterns = [
    path('', welcome, name='bienvenida'),
    path('acceso/', LoginView.as_view(), name='acceso'),
    path('talleres/', Talleres.as_view(), name='talleres'),
    path('view/<int:pk>', Detail.as_view(), name="detail"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

core/urls.py
from django.urls import path
from .views import IndexView, DeleteImage, Detail, Talleres, CambioPass
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido
from django.urls import include

app_name = 'dashboard'

urlpatterns = [
    path('', login_requerido(IndexView.as_view()), name="index"),
    path('delete/<int:pk>', DeleteImage.as_view(), name="delete"),
    path('view/<int:pk>', Detail.as_view(), name="detail"),
    path('talleres', login_requerido(Talleres.as_view()), name="talleres"),
    path('cambiopass', CambioPass.as_view(), name="cambiopass"),
]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido

urlpatterns = [
    path('dashboard/',  decorator_include(login_requerido, include('core.urls'))),
    path('', include('acceso.urls')),
    path('verification/', include('verify_email.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

acceso/forms.py
from datetime import date

from django import forms

from acceso.models import Usuario
from core.models import ComentarioEvaluacion

import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NOMBRE_REGEX = re.compile(
    r'^([a-zA-Z ]{2,254})')


class UsuarioForm(forms.ModelForm):

    # agregar validaciones de email, nombre, apellido, contraseña, telefono

    confirmar_password = forms.CharField(
        label="Confirmar Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_nombre(self):
        nombre = self.cleaned_data['nombre']
        if len(nombre) < 2:
            raise forms.ValidationError(
                'Nombre debe tener minimo 2 caracteres ')
        if not NOMBRE_REGEX.match(nombre):
            raise forms.ValidationError('Nombre Solo debe contener letras')
        return nombre

    def clean_apellido(self):
        apellido = self.cleaned_data['apellido']
        if len(apellido) < 2:
            raise forms.ValidationError(
                'apellido debe tener minimo 2 caracteres')
        if not NOMBRE_REGEX.match(apellido):
            raise forms.ValidationError('apellido Solo debe contener letras')
        return apellido

    def clean_email(self):
        email = self.cleaned_data['email']
        if not EMAIL_REGEX.match(email):
            raise forms.ValidationError(
                'Ingresar formato válido de Correo Electronico')
        return email

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)

        if cleaned_data.get('password') != cleaned_data.get('confirmar_password'):
            raise forms.ValidationError(
                "Las contraseñas no coinciden"
            )

    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'username', 'email', 'password']

        labels = {
            'nombre': 'Nombre: ',
            'apellido': 'Apellido: ',
            'username': 'Nombre Usuario: ',
            'email': 'Correo: ',
            'password': 'Contraseña: ',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = ComentarioEvaluacion
        fields = ['evaluacion', 'nombre', 'comentario']

        labels = {
            'evaluacion': 'Evaluación: ',
            'nombre': 'Nombre: ',
            'comentario': 'Comentario: ',
        }

        widgets = {
            'evaluacion': forms.TextInput(attrs={'class': 'rating', 'id': 'input-id', 'value': '0', 'type': 'text', 'data-min': '0', 'data-max': '5', 'data-step': '0.5', 'data-size': 'xs', 'name': 'evaluacion', 'tabindex': '-1', 'required': True}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'comentario': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'required': True}),
        }


class change_password_Form(forms.ModelForm):

    # agregar validaciones de email, nombre, apellido, contraseña, telefono

    confirmar_password = forms.CharField(
        label="Confirmar nueva contraseña: ", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)

        if cleaned_data.get('password') != cleaned_data.get('confirmar_password'):
            raise forms.ValidationError(
                "Las contraseñas no coinciden"
            )

    class Meta:
        model = Usuario
        fields = ['password']

        labels = {
            'password': 'Nueva contraseña: ',
        }

        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Usuario',
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Usuario o Email'})
    )

    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )


class ForgetPass(LoginForm):
    password = None
    username = forms.CharField(
        label='Usuario o Email:',
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control'})
    )

acceso/views.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.db.models import Q
from django.db.models import Avg
from decouple import config
from django.urls import reverse
from django.views import View
from django.contrib import messages
from acceso.forms import UsuarioForm, change_password_Form
from acceso.forms import ComentarioForm
from acceso.forms import LoginForm
from acceso.forms import ForgetPass
from acceso.models import Usuario
from core.models import ComentarioEvaluacion
from core.models import Imagen
import bcrypt
# email stuff
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage


mapbox_access_token = config('mapbox_access_token')


def welcome(request):
    contexto = {
        'formLogin': LoginForm()
    }
    if 'usuario' in request.session:
        messages.error(
            request, 'Ya estas logueado. Si quieres salir, click en SALIR')
        return redirect(reverse('dashboard:index'))
    return render(request, 'acceso/bienvenida.html', contexto)


class LoginView(View):
    def get(self, request):
        if ('usuario' in request.session):
            messages.error(
                request, 'Ya estas logueado. Si quieres salir, click en SALIR')
            # return redirect('/')
            return redirect(reverse('dashboard:index'))
        contexto = {
            'formRegister': UsuarioForm(),
            'formLogin': LoginForm()
        }
        return render(request, 'acceso/login.html', contexto)

    def post(self, request):
        form = UsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit=False)
            usuario.password = bcrypt.hashpw(
                usuario.password.encode(), bcrypt.gensalt()).decode()
            usuario.is_active = False
            usuario.save()
            current_site = get_current_site(request)
            mail_subject = 'Activa tu cuenta de Taller APP'
            message = render_to_string('acceso/acc_active_email.html', {
                'user': usuario,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
                'token': account_activation_token.make_token(usuario),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'acceso/verificacion.html')
        else:
            contexto = {
                'formRegister': form,
                'formLogin': LoginForm()
            }
            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'acceso/login.html', contexto)


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = Usuario.objects.filter(Q(username=form.cleaned_data['username']) | Q(
                email=form.cleaned_data['username'])).first()
            if user:
                if user.is_active == True:
                    form_password = form.cleaned_data['password']
                    if bcrypt.checkpw(form_password.encode(), user.password.encode()):
                        request.session['usuario'] = {
                            'nombre': user.nombre, 'apellido': user.apellido, 'email': user.email, 'username': user.username, 'id': user.id, 'password': user.password}
                        return redirect(reverse('dashboard:index'))
                    else:
                        messages.error(
                            request, 'Contraseña o Usuario Incorrecto')
                        return redirect(reverse('acceso:bienvenida'))
                else:
                    messages.error(
                        request, 'No has activado tu cuenta, debes hacerlo desde el correo con el que te registraste.')
                    return redirect(reverse('acceso:bienvenida'))
            else:
                messages.error(
                    request, 'Usuario No Existe, Registrate.')
                return redirect(reverse('acceso:bienvenida'))
        else:
            contexto = {
                'formRegister': UsuarioForm(),
                'formLogin': form
            }
            return render(request, 'acceso/login.html', contexto)


def logout(request):
    if 'usuario' in request.session:
        messages.success(request, 'SALISTE')
        del request.session['usuario']
    else:
        messages.error(request, 'Tu no estas logeado.')
    return redirect(reverse('acceso:bienvenida'))


class Talleres(View):
    def get(self, request):
        print('buscando error 1')
        talleres_total = Usuario.objects.all()
        lista_evaluaciones = []
        for taller in talleres_total:
            identificacion = taller.id
            evaluacion_promedio = ComentarioEvaluacion.objects.all().filter(
                usuario__id=taller.id).aggregate(Avg('evaluacion'))
            if evaluacion_promedio['evaluacion__avg'] != None:
                lista_evaluaciones.append(
                    [identificacion, evaluacion_promedio['evaluacion__avg']])
        contexto = {
            'evaluaciones': lista_evaluaciones,
            'talleres': talleres_total,
            'mapboxtoken': mapbox_access_token,
        }
        return render(request, 'acceso/talleres.html', contexto)


class Detail(View):
    def get(self, request, pk):
        usuario_detail = Usuario.objects.get(
            id=pk)
        numero = str(usuario_detail.telefono)
        numero = numero[1:]
        numeromensaje = f'https://wa.me/{numero}?text=Me%20interesa%20obtener%20mayor%20información%20de%20su%20taller'
        imagenes = Imagen.objects.all().filter(
            usuario__id=pk)
        comentarios = ComentarioEvaluacion.objects.all().filter(usuario__id=pk)
        promedio_evaluaciones = ComentarioEvaluacion.objects.all().filter(
            usuario__id=pk).aggregate(Avg('evaluacion'))
        contexto = {
            'taller': usuario_detail,
            'imagenes': imagenes,
            'comentarios': comentarios,
            'whatsapp': numeromensaje,
            'mapboxtoken': mapbox_access_token,
            'lat': str(usuario_detail.lat),
            'long': str(usuario_detail.long),
            'formComent': ComentarioForm(),
            'promedio': promedio_evaluaciones,
        }
        return render(request, 'acceso/perfil.html', contexto)

    def post(self, request, pk):
        usuario_detail = Usuario.objects.get(
            id=pk)
        formComent = ComentarioForm(request.POST)
        if formComent.is_valid():
            comentario_recibido = formComent.save(commit=False)
            comentario_recibido.usuario = usuario_detail
            comentario_recibido.save()
            messages.success(request, 'Gracias por tu evaluación!')
            return redirect(f'/view/{pk}')
        else:
            messages.error(request, 'Con errores, solucionar.')
            return redirect(f'/view/{pk}')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Usuario creado correctamente')
        return render(request, 'acceso/confirmacion.html')
    else:
        return HttpResponse('Activation link is invalid!')


def forgetpassword(request):
    if request.method == 'GET':
        contexto = {
            'forgotPasswordForm': ForgetPass()
        }
        return render(request, 'acceso/forget_password.html', contexto)

    if request.method == 'POST':
        username = request.POST.get('username')
        usuario = Usuario.objects.filter(Q(username=username) | Q(
            email=username)).first()
        if usuario is None:
            messages.error(request, 'Usuario no encontrado')
            return redirect(reverse('acceso:bienvenida'))
        else:
            current_site = get_current_site(request)
            mail_subject = 'Restore your password'
            message = render_to_string('acceso/restore_password.html', {
                'user': usuario,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(usuario.pk)),
                'token': account_activation_token.make_token(usuario),
            })
            to_email = usuario.email
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'acceso/recuperacion.html')


def restore_password(request, uidb64, token):
    if request.method == 'GET':
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = Usuario.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            contexto = {
                'change_password_Form': change_password_Form(),
                'usuario': user,
            }
        return render(request, 'acceso/restablecer_password.html', contexto)

    if request.method == 'POST':
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Usuario.objects.get(pk=uid)
        user.password = request.POST.get('password')

acceso/templates/acceso/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TALLER APP{% block titulo %}{% endblock %}</title>
    {% block redirigir %}{% endblock  %}
    {% load static %}	
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/jquery.bxslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css" rel="stylesheet">
    {% comment %} ############################################################## {% endcomment %}
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
    {% comment %} ############################################################## {% endcomment %}
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
    {% block estilos %}{% endblock %}
</head>
<body>
        {% block contenido %}{% endblock %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="{% static 'js/jquery.bxslider.js' %}"></script>
    {% comment %} ########################################################## {% endcomment %}
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/star-rating.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/locales/LANG.js"></script>
    {% comment %} ########################################################## {% endcomment %}

    <script>

        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

acceso/templates/acceso/bienvenida.html
{% extends "acceso/base.html"%}
{% load static %}

{% block titulo %} - Bienvenida{% endblock %}


{% block contenido %}
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
                <img class="logo" src="{% static 'img/bicicleta.png' %}"></img>
                <h1>TallerAPP </h1>
            </ul>
            <div class="d-flex">
                <a href="{%url 'acceso:acceso'%}" class="btn btn-primary me-2" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Registra tu Taller</a>
            </div>
            <div class="d-flex">
                <button type="button" class="btn btn-secondary" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px" data-bs-toggle="modal" data-bs-target="#exampleModal">Login</button>
            </div>
        </div>
    </div>
    </nav>
</div>

<div class="row rowbienvenida">
        <div class="col-4 imagenprincipal">
            <img class="mt-5" src="{% static 'img/imagenprincipal.jpg' %}"></img>
        </div>
        <div class="col-3 principal-body">
            <h1 class='titulo'><img class="logotitulo" src="{% static 'img/bicicleta.png' %}"></img>TallerApp</h1>
            <h1 class='subtitulo'>Encuentra los talleres de bicicleta más cercanos, estés donde estés.</h1>
            <a href="{%url 'acceso:talleres'%}" class="btn btn-talleres btn-lg btn-dark">Conoce los Talleres en tu zona</a>
        </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% comment %} ... {% endcomment %}
                <form action="{% url 'acceso:login' %}" method="post">
                        {% csrf_token %}
                        {{ formLogin.non_field_errors }}
                        {% for field in formLogin %}
                        <div class="mb-3 row">
                            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-9">
                                {{ field }}
                            </div>
                            {% if field.errors %}
                            <div class="alert alert-danger mt-2" role="alert">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <hr>
                        <div class="">
                            <div class="row">
                                <div class="col-6 d-inline-flex">
                                    <a href="{% url 'acceso:forgetpassword' %}">¿Olvidaste tu contraseña?</a>
                                </div>
                                <div class="col-6 d-inline-flex flex-row-reverse">
                                    <button class="btn btn-success" type="submit" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Entrar</button>
                                    <button type="button" class="btn btn-secondary me-2" data-bs-dismiss="modal" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Cancelar</button>
                                </div>
                            </div>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
var myModal = document.getElementById('myModal')
var myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', function () {
  myInput.focus()
})
</script>

{% endblock %}

acceso/templates/acceso/talleres.html
{% extends "acceso/base.html"%}
{% load static %}
{% load l10n %}

{% block titulo %} - Todos los Talleres{% endblock %}

{% block estilos %}

<style>

</style>

{% endblock %}
{% block contenido %}

<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
                    <img class="logo" src="{% static 'img/bicicleta.png' %}"></img>
                    <h1>TallerAPP </h1>
                </ul>
                <div class="d-flex">
                    <a href="{%url 'acceso:bienvenida'%}" class="btn btn-success"style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Inicio</a>
                </div>
                <div class="d-flex">
                    <a href="{%url 'acceso:acceso'%}" class="btn btn-primary ms-2 me-2" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px; color:white; justify-content:center">Registra tu Taller</a>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class='row'>
    <div class="container col-8 mt-5">
        <h3>Encuentra los talleres más cercanos a tu ubicación</h3>
        <hr>
    </div>
</div>
<div class='row'>
    <div class="container contenedor-mapa d-flex col-7 mt-1">
        <div class="d-flex justify-content-center border-5 border" id='map' style='width: 1000px; height: 600px;'></div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
mapboxgl.accessToken = '{{mapboxtoken}}';
var map = new mapboxgl.Map({
container: 'map', // container ID
style: 'mapbox://styles/mapbox/streets-v11', // style URL
center: [-70.63441111,-33.437], // starting position [lng, lat]
zoom: 15 // starting zoom
});

map.addControl(
new MapboxGeocoder({
accessToken: '{{mapboxtoken}}',
mapboxgl: mapboxgl
})
);

const geolocate = new mapboxgl.GeolocateControl({
        positionOptions: {
enableHighAccuracy: true
},
// When active the map will receive updates to the device's location as it changes.
trackUserLocation: true,
// Draw an arrow next to the location dot to indicate which direction the device is heading.
showUserHeading: true
})
map.addControl(geolocate)

map.on('load', function()
{
	geolocate.trigger();
});

geolocate.on('geolocate', function()
{

//Get the updated user location, this returns a javascript object.
var userlocation = geolocate._lastKnownPosition;

//Your work here - Get coordinates like so
var lat = userlocation.coords.latitude;
var lng = userlocation.coords.longitude;
});


{% for taller in talleres %}
    {% for evaluacion in evaluaciones %}
        {% if evaluacion.0 != taller.id %}
            var marker = new mapboxgl.Marker()
            .setLngLat([{% localize off %}{{taller.long}}{% endlocalize %},{% localize off %}{{taller.lat}}{% endlocalize %}])
            .setPopup(new mapboxgl.Popup().setHTML('<h6>Taller {{taller.nombre_taller}}</h6><p>{{taller.direccion}}</p><p>Sin evaluaciones aún</p><a href="{%url "acceso:detail" pk=taller.id%}">Más detalles</a>'))
            .addTo(map);
        {% endif %}
    {% endfor %}
{% endfor %}

const star = '<img src="{% static "img/star.png" %}"></img>'

{% for taller in talleres %}
    {% for evaluacion in evaluaciones %}
        {% if evaluacion.0 == taller.id %}
            var cantidad= Math.floor({{evaluacion.1|unlocalize}})
            var marker = new mapboxgl.Marker()
            .setLngLat([{% localize off %}{{taller.long}}{% endlocalize %},{% localize off %}{{taller.lat}}{% endlocalize %}])
            .setPopup(new mapboxgl.Popup().setHTML('<h6>Taller {{taller.nombre_taller}}</h6><p>{{taller.direccion}}</p><p>Evaluacion '+ (star.repeat(cantidad)) +'</p><a href="{%url "acceso:detail" pk=taller.id%}">Más detalles</a>'))
            .addTo(map);
        {% endif %}
    {% endfor %}
{% endfor %}

</script>

{% endblock %}

acceso/templates/acceso/verificacion.html
{% extends "acceso/base.html"%}
{% load static %}


{% block titulo %} - Verificación{% endblock %}

{% block estilos %}

<style>

</style>

{% endblock %}
{% block contenido %}

<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
                    <img class="logo" src="{% static 'img/bicicleta.png' %}"></img>
                    <h1>TallerAPP </h1>
                </ul>
                <div class="d-flex">
                    <a href="{%url 'acceso:bienvenida'%}" class="btn btn-success">Inicio</a>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class='row'>
    <div class="container col-8 mt-5 text-center">
        <h3>Por favor revisa tu correo para validar tu cuenta.</h3>
    </div>
</div>

{% endblock %}