acceso/urls.py
from django.urls import path
from .views import LoginView, login, logout, welcome, Talleres, Detail

app_name = 'acceso'

urlpatterns = [
    path('', welcome, name='bienvenida'),
    path('acceso/', LoginView.as_view(), name='acceso'),
    path('talleres/', Talleres.as_view(), name='talleres'),
    path('view/<int:pk>', Detail.as_view(), name="detail"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

core/urls.py
from django.urls import path
from .views import IndexView, DeleteImage, Detail, Talleres, CambioPass
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido
from django.urls import include

app_name = 'dashboard'

urlpatterns = [
    path('', login_requerido(IndexView.as_view()), name="index"),
    path('delete/<int:pk>', DeleteImage.as_view(), name="delete"),
    path('view/<int:pk>', Detail.as_view(), name="detail"),
    path('talleres', login_requerido(Talleres.as_view()), name="talleres"),
    path('cambiopass', CambioPass.as_view(), name="cambiopass"),
]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido

urlpatterns = [
    path('dashboard/',  decorator_include(login_requerido, include('core.urls'))),
    path('', include('acceso.urls')),
    path('verification/', include('verify_email.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from acceso.models import Usuario
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.html import format_html
# Create your models here.


# class Usuario(models.Model):
#     nombre = models.CharField(max_length=50)
#     apellido = models.CharField(max_length=50)
#     username = models.CharField(
#         max_length=20, unique=True, verbose_name="Nombre de Usuario")
#     telefono = models.CharField(
#         max_length=12, unique=True, null=True, blank=True)
#     email = models.EmailField(max_length=200, unique=True)
#     propietario_taller = models.BooleanField(default=True)
#     # para efectos de la actividad, será por defecto true
#     nombre_taller = models.CharField(max_length=200, null=True, blank=True)
#     instagram = models.charField(
#         max_length=100, unique=True, null=True, blank=True)
#     facebook = models.charField(
#         max_length=100, unique=True, null=True, blank=True)
#     direccion = models.TextField(null=True, blank=True)
#     lat = models.FloatField(blank=True, null=True)
#     long = models.FloatField(blank=True, null=True)
#     password = models.CharField(max_length=72)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
# images: lista de imagenes asociadas a un taller
# comentarios: lista de comentarios asociados a un taller

class Imagen(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    usuario = models.ForeignKey(
        Usuario, related_name="images", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return format_html('<p>{}</p>', f'{self.usuario}') + format_html('<img src="{}" width="100" />', f'{self.image.url}')


class ComentarioEvaluacion(models.Model):
    usuario = models.ForeignKey(
        Usuario, related_name="comentarios", on_delete=models.CASCADE)
    # Despues de comprobar si todo funciona correctamente, cambiar a False
    nombre = models.CharField(max_length=50, blank=True, null=True)
    comentario = models.TextField(max_length=350, blank=True, null=True)
    evaluacion = models.FloatField(
        validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    # evaluacion = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Dueño taller: {self.usuario}, Comentario de: {self.nombre}, Comentario: {self.comentario}"

core/forms.py
from datetime import date

from django import forms

from acceso.models import Usuario

from acceso.forms import UsuarioForm

from .models import Imagen

import re


class UsuarioFormDetalle(UsuarioForm):
    confirmar_password = None

    class Meta:
        model = Usuario
        fields = ['nombre_taller', 'direccion', 'telefono',
                  'instagram', 'facebook', 'descripcion']

        labels = {
            'nombre_taller': 'Nombre de tu Taller: ',
            'direccion': 'Dirección: ',
            'telefono': 'Número de contacto, Whatsapp: ',
            'instagram': 'Link Instagram: ',
            'facebook': 'Link Facebook: ',
            'descripcion': 'Describe tus Servicios:',
        }

        widgets = {
            'nombre_taller': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'id': 'searchTextField', 'required': True}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'instagram': forms.TextInput(attrs={'class': 'form-control'}),
            'facebook': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
        }


class UsuarioFormBasico(UsuarioForm):
    confirmar_password = None

    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'username', 'email']

        labels = {
            'nombre': 'Nombre: ',
            'apellido': 'Apellido: ',
            'username': 'Nombre Usuario: ',
            'email': 'Correo: ',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'}),
        }


class ImageForm(forms.ModelForm):

    # def clean(self):
    #     cleaned_data = super().clean()
    #     image = cleaned_data.get('image')
    #     print(cleaned_data)
    #     if image:
    #         imagename = image.image
    #         print(imagename)
    #         if imagename.endswith('.jpg'):
    #             print('File is a jpg')
    #         else:
    #             print('File is NOT a jpg')
    #             raise forms.ValidationError(
    #                 "Este archivo no es una imagen formato JPG")

    # if not cleaned_data.get('image').endswith('.jpg'):
    #     raise forms.ValidationError(
    #         "Las contraseñas no coinciden"
    #     )

    class Meta:
        model = Imagen
        fields = ['image']

        labels = {
            'image': 'Imagen (máx 2mb):'
        }

        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control form-control-sm', 'type': 'file', 'id': 'formFileSm', 'accept': 'images/'}),
        }

core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Avg
from decouple import config
from acceso.utils.decoradores import login_requerido
from acceso.models import Usuario
from .models import Imagen
from .models import ComentarioEvaluacion
import bcrypt
from acceso.forms import UsuarioForm
from core.forms import UsuarioFormBasico
from core.forms import UsuarioFormDetalle
from core.forms import ImageForm
from core.forms import Cambiopassword
from django.views import View
from django.contrib import messages
from django.db.models import Q, Count
from django.contrib.auth.decorators import user_passes_test

mapbox_access_token = config('mapbox_access_token')
google_access_token = config('google_access_token')


class IndexView(View):
    def get(self, request):
        usuario_detail = Usuario.objects.get(
            id=request.session['usuario']['id'])
        form = UsuarioFormBasico(instance=usuario_detail)
        form_det = UsuarioFormDetalle(instance=usuario_detail)
        form_img = ImageForm(instance=usuario_detail)
        imagenes = Imagen.objects.all().filter(
            usuario__id=request.session['usuario']['id'])
        contexto = {
            'usuariodetalles': usuario_detail,
            'formModel': form,
            'formModelDet': form_det,
            'formModelImg': form_img,
            'formImg': form_img,
            'imagenes': imagenes,
            'googletoken': google_access_token
        }
        u1 = Usuario.objects.get(id=request.session['usuario']['id'])
        if u1.is_active is True:
            return render(request, 'core/index.html', contexto)
        else:
            return redirect(reverse('acceso:bienvenida'))

    def post(self, request):
        usuario_detail = Usuario.objects.get(
            id=request.session['usuario']['id'])
        form = UsuarioFormBasico(request.POST, instance=usuario_detail)
        form_det = UsuarioFormDetalle(request.POST, instance=usuario_detail)
        form_img = ImageForm(request.POST, request.FILES)
        image = request.FILES.get('image')
        imagenes = Imagen.objects.all().filter(
            usuario__id=request.session['usuario']['id'])
        if len(request.FILES) > 0:
            if imagenes.count() < 3:
                if form_img.is_valid() and request.FILES.get('image') != None:
                    Imagen.objects.create(image=image, usuario=usuario_detail)
                    messages.success(request, 'Imagen Cargada Correctamente.')
                    return redirect(reverse('dashboard:index'))
                else:
                    messages.error(request, 'No se ha cargado ninguna imagen.')
                    return redirect(reverse('dashboard:index'))
            else:
                messages.error(request, 'Máximo 3 imágenes.')
                return redirect(reverse('dashboard:index'))
        elif request.POST.get('form') == 'basico':
            if form.is_valid():
                form.save()
                messages.success(request, 'Datos Editados Correctamente.')
                return redirect(reverse('dashboard:index'))
            else:
                messages.error(request, 'Con errores, solucionar.')
                return redirect(reverse('dashboard:index'))
        elif request.POST.get('form') == 'datos':
            if form_det.is_valid():
                form_det.save()
                messages.success(
                    request, 'Datos de Taller Actualizados Correctamente.')
                return redirect(reverse('dashboard:index'))
            else:
                messages.error(request, 'Con errores, solucionar.')
                return redirect(reverse('dashboard:index'))
        else:
            messages.error(request, 'Este formulario no existe.')
            return redirect(reverse('dashboard:index'))


class DeleteImage(View):
    def get(self, request, pk):
        imagen_delete = Imagen.objects.get(id=pk)
        if request.session['usuario']['id'] == imagen_delete.usuario.id:
            imagen_delete.delete()
            messages.success(request, 'Imagen eliminada correctamente.')
            return redirect(reverse('dashboard:index'))
        else:
            messages.error(
                request, 'Esta imagen no fue subida por ti, no puedes editar.')
            return redirect(reverse('dashboard:index'))


class Detail(View):
    def get(self, request, pk):
        usuario_detail = Usuario.objects.get(
            id=pk)
        numero = str(usuario_detail.telefono)
        numero = numero[1:]
        numeromensaje = f'https://wa.me/{numero}?text=Me%20interesa%20obtener%20mayor%20información%20de%20su%20taller'
        imagenes = Imagen.objects.all().filter(
            usuario__id=pk)
        comentarios = ComentarioEvaluacion.objects.all().filter(usuario__id=pk)
        promedio_evaluaciones = ComentarioEvaluacion.objects.all().filter(
            usuario__id=pk).aggregate(Avg('evaluacion'))
        contexto = {
            'taller': usuario_detail,
            'imagenes': imagenes,
            'comentarios': comentarios,
            'whatsapp': numeromensaje,
            'mapboxtoken': mapbox_access_token,
            'lat': str(usuario_detail.lat),
            'long': str(usuario_detail.long),
            'promedio': promedio_evaluaciones,
        }
        return render(request, 'core/perfil.html', contexto)


class Talleres(View):
    def get(self, request):
        talleres_total = Usuario.objects.all()
        lista_evaluaciones = []
        for taller in talleres_total:
            identificacion = taller.id
            evaluacion_promedio = ComentarioEvaluacion.objects.all().filter(
                usuario__id=taller.id).aggregate(Avg('evaluacion'))
            if evaluacion_promedio['evaluacion__avg'] != None:
                lista_evaluaciones.append(
                    [identificacion, evaluacion_promedio['evaluacion__avg']])
        contexto = {
            'evaluaciones': lista_evaluaciones,
            'talleres': talleres_total,
            'mapboxtoken': mapbox_access_token,
        }
        return render(request, 'core/talleres.html', contexto)


class CambioPass(View):
    def get(self, request):
        form = Cambiopassword()
        contexto = {
            'formModel': form,
        }
        return render(request, 'core/cambiopass.html', contexto)

    def post(self, request):
        if request.session['usuario']:
            form = Cambiopassword(request.POST)
            if form.is_valid():
                user = Usuario.objects.filter(Q(username=request.session['usuario']['username']) | Q(
                    email=request.session['usuario']['email'])).first()
                if user:
                    form_password = form.cleaned_data['new_password']
                    if bcrypt.checkpw(form_password.encode(), user.password.encode()):
                        if request.POST['password'] == request.POST['confirmar_new_password']:
                            usuario_form = form.save(commit=False)
                            nueva_contraseña = bcrypt.hashpw(
                                usuario_form.password.encode(), bcrypt.gensalt()).decode()
                            usuario_detail = Usuario.objects.get(
                                id=request.session['usuario']['id'])
                            usuario_detail.password = nueva_contraseña
                            usuario_detail.save()
                            messages.success(
                                request, 'Contraseña Actualizada con exito.')
                            return redirect(reverse('dashboard:index'))
                        else:
                            messages.error(
                                request, 'Las nuevas contraseñas no coinciden.')
                            return redirect(reverse('dashboard:cambiopass'))
                    else:
                        messages.error(
                            request, 'Contraseña actual no válida.')
                        return redirect(reverse('dashboard:cambiopass'))
            else:
                messages.error(
                    request, 'Informacion ingresada Con errores, solucionar')
                return redirect(reverse('dashboard:cambiopass'))
        else:
            messages.error(request, 'Tu no estas logeado.')
            return redirect(reverse('acceso:bienvenida'))

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taller App - {% block titulo %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.bxslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    {% comment %} ############################################################## {% endcomment %}
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
    {% comment %} ############################################################## {% endcomment %}
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block googleapi %}{% endblock  %}
    {% block estilos %}{% endblock %}
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark text-white">
<div class="container-fluid">
    {% block tituloNav %}{% endblock  %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
            <div class="d-flex me-2">
                {% block botonone %}{% endblock %}
            </div>
            <div class="d-flex me-2">
                {% block botontwo %}{% endblock %}
            </div>
            <div class="d-flex">
                <a href="{% url 'acceso:logout' %}" class="btn btn-danger" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">SALIR</a>
            </div>
    </div>
</div>
</nav>
    <div class="main">
        {% block contenido %}{% endblock %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/jquery.bxslider.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>
    {% comment %} ########################################################## {% endcomment %}
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/star-rating.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/js/locales/LANG.js"></script>
    {% comment %} ########################################################## {% endcomment %}

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

core/templates/core/cambiopass.html
{% extends "core/base.html"%}
{% load static %}
{% load l10n %}

{% block titulo %}Cambio Contraseña{% endblock %}

{% block estilos %}

{% endblock %}
{% block tituloNav %}<img class="logo" src="{% static 'img/bicicleta.png' %}"></img>
                <h2>TallerAPP</h2>{% endblock  %}
{% block botonone %}<a href="{%url 'dashboard:talleres'%}" class="btn btn-primary" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Todos los Talleres</a>{% endblock %}
{% block botontwo %}<a href="{%url 'dashboard:index'%}" class="btn btn-warning" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">DashBoard</a>{% endblock %}
{% block contenido %}


<div class="container col-12 mt-5">
    <div class=" ms-5 me-5 col-5">
        <h3>Ingresa los campos Requeridos</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ formModel.non_field_errors }}
                    {% for field in formModel %}
                    <div class="mb-3 row">
                        <label for="{{ field.id_for_label }}" class="col-5 col-form-label">{{ field.label }}</label>
                        <div class="col-7">
                            {{ field }}
                        </div>
                        {% if field.errors %}
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="col-7 d-inline-flex flex-row-reverse mt-2">
                        <a href="{%url 'dashboard:index'%}" class="btn btn-secondary" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Cancelar</a>
                    </div>
                    <div class="col-4 d-inline-flex flex-row-reverse mt-2">
                        <button class="btn btn-warning" type="submit" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px; color:white; justify-content:center">Editar </button>
                    </div>
                </form>
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html"%}
{% load static %}

{% block titulo %}Dashboard{% endblock %}
{% block googleapi %}<script src="https://maps.googleapis.com/maps/api/js?key={{googletoken}}&v=3.exp&sensor=false&libraries=places"></script>{% endblock  %}

{% block estilos %}

<style>

    .imagenDashboard{
        width: 200px;
        height: 140px
    }

    .formulario{
        background-color:rgb(224, 212, 253);
    }
</style>

{% endblock %}
{% block tituloNav %}<img class="logo" src="{% static 'img/bicicleta.png' %}"></img>
                <h2>TallerAPP - DashBoard</h2>{% endblock  %}
{% block botonone %}<a href="{%url 'dashboard:talleres'%}" class="btn btn-primary" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px" >Todos los Talleres</a>{% endblock %}
{% block botontwo %}
{% if usuariodetalles.direccion %}
<a href="{%url 'dashboard:detail' pk=request.session.usuario.id%}" class="btn btn-success" style="background-color: white; color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 150px">Tu Perfil</a>
{% endif %}
{% endblock %}
{% block contenido %}
{% block googletoken %}<script src="https://maps.googleapis.com/maps/api/js?key={{googletoken}}&v=3.exp&sensor=false&libraries=places"></script>{% endblock  %}
<div class='row'>
    <div class="container col-10 mt-5">
        <h2><b>{{request.session.usuario.nombre}},</b> en este espacio puedes actualizar todos tus datos.</h2>
        <hr>
    </div>
</div>
<div class="container col-12">
        <div class="row formulario">
            <div class=" ms-5 me-5 mt-2 col-md-4">
                <h3>Editar tus datos Básicos</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ formModel.non_field_errors }}
                    {% for field in formModel %}
                    <div class="mb-3 row">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                        </div>
                        {% if field.errors %}
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <input type="hidden" name='form' value='basico'>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-warning d-flex mb-2" type="submit" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 100px; color:white; justify-content:center">   Editar</button>
                    </div>
                </form>
                <hr>
                <div>
                    <div class="d-inline-block me-4">
                        <h5>Cambio Contraseña</h5>
                    </div>
                    <div class="col-6 d-inline-flex flex-row-reverse mt-2">
                        <a href="{%url 'dashboard:cambiopass'%}" class="btn btn-primary" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 100px; color:white; justify-content:center">Cambiar</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 ms-5 me-5">
                <h3>Agrega los datos de tu taller</h3>
                <hr>
    
                <form action="" method="post">
                
                    {% csrf_token %}
                    {{ formLogin.non_field_errors }}
    
                    {% for field in formModelDet %}
                    <div class="mb-3 row">
    
    
                        <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-7">
                            {{ field }}
                        </div>
    
                        {% if field.errors %}
    
                        <div class="alert alert-danger mt-2" role="alert">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
    
                        {% endif %}
    
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <input type="hidden" name='form' value='datos'>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button class="btn btn-success d-flex mb-2" type="submit" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 100px; color:white; justify-content:center">Actualizar</button>
                    </div>
                </form>
                <h3>Agrega Imágenes</h3>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ formImg.non_field_errors }}

                    {% for field in formImg %}
                <div class="mb-3 row">

                <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                <div class="col-sm-9">
                    {{ field }}
                </div>
                {% if field.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
                </div>
                {% endfor %}
                <div class="col-12 d-flex flex-row-reverse mt-2">
                    <button class="btn btn-primary offset-3" type="submit" style="background-color:#6E7DE4; border-color: #6E7DE4; border-radius:20px; width: 100px; color:white; justify-content:center">Agregar</button>
                </div>
                </form>
                </form>
                {% if imagenes %}
                <div class='mt-3'>
                <h3>Tus Imágenes Cargadas</h3>
                <hr>
                    {% for imagen in imagenes %}
                    <div class="d-inline-block">
                    <a data-fancybox="gallery" href="/media/{{imagen.image}}">
                        <img class="imagenDashboard border border-danger"src="/media/{{imagen.image}}"></img>
                    </a>
                    <div class="d-grid gap-2 d-flex justify-content-end">
                        <a href="{%url 'dashboard:delete' pk=imagen.id%}" class="btn btn-danger btn-sm d-flex mb-2 mt-1">Eliminar</a>
                    </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
</div>

{% endblock %}

{% block scripts %}
<script>

let places, input, address, city;
google.maps.event.addDomListener(window, "load", function () {

    var places = new google.maps.places.Autocomplete(
        document.getElementById("searchTextField")
    );
    google.maps.event.addListener(places, "place_changed", function () {

        var place = places.getPlace();
        console.log(place)

    })

})

Fancybox.bind('[data-fancybox="gallery"]', {
        infinite: true
    });

</script>

{% endblock %}